language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
  - /^deploy-.*$/
email:
  recipients:
    - gvagenas@telestax.com
    - jean.deruelle@telestax.com
  on_success: never # default: change
  on_failure: always # default: always
cache:
  directories:
  - $HOME/.m2
addons:
  sonarqube:
    organization: "restcomm-connect" # the key of the org you chose at step #3
script:
  - ./build.sh
  # other script steps might be done before running the actual SonarQube analysis
  - echo "About to run sonar-scanner"
  - cd restcomm
  - sed -i 's/DEBUG/OFF/g' restcomm.testsuite/src/test/resources/log4j.xml
  - sed -i 's/INFO/OFF/g' restcomm.testsuite/src/test/resources/log4j.xm
  - sed -i 's/DEBUG/OFF/g'  restcomm.testsuite/src/test/resources/akka_application.conf
  - mvn -q clean org.jacoco:jacoco-maven-plugin:prepare-agent surefire-report:report sonar:sonar
