language: java
jdk:
  - oraclejdk8
email:
  recipients:
    - gvagenas@telestax.com
    - jean.deruelle@telestax.com
  on_success: never # default: change
  on_failure: always # default: always
cache:
  directories:
  - $HOME/.m2
addons:
  sonarqube:
    organization: "restcomm-connect" # the key of the org you chose at step #3
script:
  - ./build.sh
  # other script steps might be done before running the actual SonarQube analysis
  - echo "About to run sonar-scanner"
  - sonar-scanner
